# Generated by Django 5.2 on 2025-06-09 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gdd',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='gdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='editor.gdd'),
        ),
        migrations.AddField(
            model_name='note',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='editor.note'),
        ),
        migrations.AddField(
            model_name='notelink',
            name='from_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='editor.note'),
        ),
        migrations.AddField(
            model_name='notelink',
            name='to_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='editor.note'),
        ),
        migrations.AddField(
            model_name='notetag',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.note'),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='gdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='editor.gdd'),
        ),
        migrations.AddField(
            model_name='note',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.notetemplate'),
        ),
        migrations.AddField(
            model_name='tag',
            name='gdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='editor.gdd'),
        ),
        migrations.AddField(
            model_name='notetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tag'),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='notes', through='editor.NoteTag', to='editor.tag'),
        ),
    ]
